sudo: false
language: node_js
node_js:
  - "10"
cache: yarn
install:
  - yarn --pure-lockfile
script:
  - yarn test:ci
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
